# Generated by Django 4.2.13 on 2024-06-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created", "-updated"]},
        ),
    ]
