# Generated by Django 4.2.13 on 2024-06-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
